### ISSUE TITLE
Não consigo utilizar

### ISSUE THREAD

**Issue by SrDavidBarbosa** [RafaelGoulartB/next-ecommerce#59]
Virei à noite tentando usar seu projeto, mas não consegui.
Não consegui conectar no banco de dados, não consegui fazer funcionar para produção.
É uma pena, pois parece muito bom

**Comment by RafaelGoulartB** [comment]
Olá @SrDavidBarbosa, talvez seja porque vc não rodou as migrations e os seeds do banco de dados.
Tenta seguir o passo a posso:

* Instalar Dependencias
`yarn install` ou `npm intsall`

* Criar banco de dados usando migrations
`yarn knex:migrate` ou  `npm run knex:migrate`

* Para rodar as seeds do Banco de dados
`yarn knex:seed`  ou `npm run knex:seed `

* Para rodar
`yarn dev`  ou `npm run dev `

Se não der certo, me manda qual erro que ta dando na hora de rodar o projeto que eu tento ver o que é o problema.

Espero ter ajudado. :)
